# Generated by Django 4.2.5 on 2023-09-08 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project Name', max_length=50)),
                ('creation_time', models.DateTimeField(auto_now_add=True, help_text='Project creation time.')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task Title', max_length=50)),
                ('description', models.TextField(help_text='Task Description')),
                ('time_estimate', models.IntegerField(help_text='Task Time Estimate')),
                ('project', models.ForeignKey(help_text='Project', on_delete=django.db.models.deletion.CASCADE, to='projectm.project')),
            ],
        ),
    ]
